# Default values for weatherapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: wakki83/weatherapp
  tag: v1
  pullPolicy: Always

replicaCount: 1

environment:
  production: true
  productionReplicaCount: 2

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

application:
  version: v1
  appId: ecbd92ff90840c3a36dad8d16f7f7fb2
  defaultCity: ""

ingress:
  host: "weather.157.230.74.199.nip.io"
  port: 80
