apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}-vsc"
  namespace: default
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
  - "{{ .Release.Name }}-gw"
  http:
  - route:
    - destination:
        host: {{ include "weatherapp.fullname" . }}
